---
name: Release

on:
  release:
    types: [published]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create package
        run: composer archive

      - name: Upload ZIP to the release
        uses: softprops/action-gh-release@v2
        with:
          files: mime-mail-parser-${{ env.RELEASE_TAG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}