---
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Get tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create package
        run: composer archive --format=zip --file="mime-mail-parser-${{ steps.tag.outputs.tag }}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: mime-mail-parser-${{ steps.tag.outputs.tag }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
